'use client';
import { ArrowUpRight, Check, Code2, ExternalLink, Mail, BookOpen, Link2, MessageCircle } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { profile, technologies, services, languages, areteFeatures } from '@/content/portfolio';
export type Panel = 'sobre'|'experiencia'|'arete'|'proximo'|'contato'|null;
const titles={sobre:'Além do código.',experiencia:'Da ideia à experiência.',arete:'Areté',proximo:'O próximo mergulho.',contato:'Vamos criar algo?'};
const descriptions={sobre:'Lógica, criatividade e uma curiosidade que não para na superfície.',experiencia:'Tecnologias e possibilidades que fazem parte do meu trabalho.',arete:'Um SaaS de produtividade e organização pessoal em desenvolvimento.',proximo:'Há sempre um novo universo para explorar.',contato:'Tecnologia e boas ideias começam com uma conversa.'};
function OutLink({href,children}:{href:string;children:React.ReactNode}){return <a className="detail-link" href={href} target="_blank" rel="noopener noreferrer">{children}<ArrowUpRight size={16}/></a>}
export default function DetailPanels({panel,onClose}:{panel:Panel;onClose:()=>void}){
 return <Dialog open={panel!==null} onOpenChange={open=>{if(!open)onClose()}}><DialogContent className="detail-dialog"><div className="detail-heading"><span className="eyebrow">RENAN / {panel==='arete'?'PROJETO EM DESTAQUE':panel==='sobre'?'SOBRE MIM':panel==='experiencia'?'TECNOLOGIAS & CRIAÇÃO':panel==='contato'?'CONTATO':'EM BREVE'}</span><DialogTitle className="detail-title">{panel?titles[panel]:''}</DialogTitle><DialogDescription className="detail-description">{panel?descriptions[panel]:''}</DialogDescription></div>
  {panel==='sobre'&&<div className="detail-body"><p className="lead">Sou Renan, desenvolvedor Full Stack. Crio aplicações web, SaaS, landing pages e experiências digitais imersivas.</p><p>Tenho cerca de 1 ano de experiência prática, construindo projetos reais e evoluindo a cada desafio. Meu foco está em interfaces modernas, responsivas e performáticas, combinando front-end avançado, back-end em .NET e atenção à experiência do usuário.</p><p>Meu trabalho vai além das páginas tradicionais: animações complexas, interfaces interativas, experiências 3D, autenticação, dashboards e aplicações preparadas para produção.</p><div className="detail-divider"/><h3>Entre lógica e literatura</h3><p>Também sou autor de dois livros publicados na Amazon e estudante de cálculo. A escrita e a matemática complementam minha maneira de pensar sobre estrutura, criatividade e resolução de problemas.</p><div className="author-links">{profile.books.map(b=><OutLink key={b.title} href={b.url}><BookOpen size={16}/>{b.title}</OutLink>)}</div><h3>Idiomas</h3><dl className="language-list">{languages.map(([language,level])=><div key={language}><dt>{language}</dt><dd>{level}</dd></div>)}</dl></div>}
  {panel==='experiencia'&&<div className="detail-body"><div className="technology-grid">{technologies.map(group=><section className="technology-group" key={group.title}><span className="eyebrow">{group.label}</span><h3>{group.title}</h3><div className="tech-tags">{group.items.map(t=><span key={t}>{t}</span>)}</div></section>)}</div><div className="detail-divider"/><h3>O que eu desenvolvo</h3><ul className="services-list">{services.map(s=><li key={s}><Check size={15}/>{s}</li>)}</ul><p className="detail-note">Experiência prática construída em projetos próprios. Sem números inflados, sem promessas genéricas.</p></div>}
  {panel==='arete'&&<div className="detail-body"><div className="arete-banner"><span>α</span><div><span className="eyebrow">SAAS EM DESENVOLVIMENTO</span><h3>Transformar intenção em ação.</h3></div></div><p className="lead">Areté é um SaaS em desenvolvimento que reúne metas, tarefas, hábitos, diário, jornadas e dashboard em uma experiência de organização pessoal.</p><div className="feature-grid">{areteFeatures.map(([title,text],i)=><section key={title}><span className="feature-number">0{i+1}</span><h3>{title}</h3><p>{text}</p></section>)}</div><h3>Do produto à produção</h3><p>O projeto está em desenvolvimento e envolve produto, arquitetura, front-end, back-end, segurança e experiência do usuário — incluindo a experiência pós-login e a preparação para produção.</p>{profile.areteUrl?<OutLink href={profile.areteUrl}>Visitar Areté</OutLink>:<p className="availability-note"><span className="status-dot"/>Areté está em desenvolvimento. O link público será adicionado quando estiver disponível.</p>}</div>}
  {panel==='proximo'&&<div className="detail-body"><div className="coming-next"><Code2 size={35}/><h3>{profile.nextProject.title}</h3><p>{profile.nextProject.description}</p><span className="eyebrow">NOVAS IDEIAS ESTÃO A CAMINHO</span></div>{profile.nextProject.url&&<OutLink href={profile.nextProject.url}>Explorar projeto</OutLink>}<OutLink href={profile.website}>Enquanto isso, conheça Emericpoeta</OutLink></div>}
  {panel==='contato'&&<div className="detail-body"><p className="lead">Aplicações web, produtos digitais e experiências que deixam uma impressão.</p><p>Uma ideia merece cuidado do primeiro esboço aos últimos detalhes. Explore meus projetos para conhecer o que estou construindo.</p><div className="contact-links">{profile.email&&<a className="detail-link" href={'https://mail.google.com/mail/?view=cm&fs=1&to='+encodeURIComponent(profile.email)} target="_blank" rel="noopener noreferrer" aria-label={'Escrever para '+profile.email+' no Gmail'}><Mail size={17}/>{profile.email}<ArrowUpRight size={16}/></a>}{profile.whatsapp&&<OutLink href={'https://wa.me/'+profile.whatsapp.replace(/\D/g,'')}><MessageCircle size={17}/>Conversar pelo WhatsApp</OutLink>}{profile.github&&<OutLink href={profile.github}><Code2 size={17}/>GitHub</OutLink>}{profile.linkedin&&<OutLink href={profile.linkedin}><Link2 size={17}/>LinkedIn</OutLink>}<OutLink href={profile.website}><ExternalLink size={17}/>Conheça meu universo autoral</OutLink></div>{!profile.email&&!profile.whatsapp&&<p className="availability-note"><Mail size={15}/>Meus canais de contato profissional serão adicionados em breve.</p>}</div>}
 </DialogContent></Dialog>;
}

