'use client';
import { lazy, Suspense, useEffect, useState } from 'react';
import { ArrowDown, ArrowUpRight, ArrowRight, Code2, Compass, BookOpen, House, Layers3, UserRound, Mail, Sparkles, Pause, Play, Waves, PanelTop } from 'lucide-react';
import { Button } from '@/components/ui/button';
import OceanScene from '@/components/ocean-scene';
import { profile } from '@/content/portfolio';
import type { Panel } from '@/components/detail-panels';
const DetailPanels=lazy(()=>import('@/components/detail-panels'));
const panelIds=['sobre','experiencia','arete','proximo','contato'];
export default function Portfolio() {
 const [section,setSection]=useState('inicio');
 const [panel,setPanel]=useState<Panel>(null),[paused,setPaused]=useState(true),[immersive,setImmersive]=useState(false);
 useEffect(()=>{
  const preference=matchMedia('(prefers-reduced-motion: reduce)');
  const syncMotion=()=>{let saved:string|null=null;try{saved=localStorage.getItem('renan-motion-v1')}catch{}setPaused(saved?saved==='paused':preference.matches)};
  const syncRoute=()=>{const id=location.hash.slice(1);setPanel(panelIds.includes(id)?id as Panel:null);setSection(id||'inicio')};
  const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')setImmersive(false)};
  syncMotion();syncRoute();preference.addEventListener('change',syncMotion);window.addEventListener('hashchange',syncRoute);window.addEventListener('popstate',syncRoute);window.addEventListener('keydown',escape);
  return()=>{preference.removeEventListener('change',syncMotion);window.removeEventListener('hashchange',syncRoute);window.removeEventListener('popstate',syncRoute);window.removeEventListener('keydown',escape)};
 },[]);
 function navigate(id:string){setSection(id);setImmersive(false);history.pushState(null,'','#'+id);if(panelIds.includes(id)){setPanel(id as Panel)}else{setPanel(null);document.getElementById(id)?.scrollIntoView({behavior:paused?'instant':'smooth',block:'start'})}}
 function closePanel(){setPanel(null);setSection('inicio');history.replaceState(null,'',location.pathname+location.search)}
 function toggleMotion(){const next=!paused;setPaused(next);try{localStorage.setItem('renan-motion-v1',next?'paused':'playing')}catch{}}
 return <main className="portfolio" id="inicio" data-paused={paused} data-immersive={immersive}>
  <a className="skip-link" href="#projetos">Pular para os projetos</a>
  <div className="ocean-backdrop" aria-hidden="true"/><div className="ocean-shade" aria-hidden="true"/>
  <OceanScene paused={paused}/>
  <header className="site-header"><a className="wordmark" href="#inicio" onClick={e=>{e.preventDefault();navigate('inicio')}}><span className="monogram">R.</span><span>RENAN<small>DESENVOLVEDOR FULL STACK</small></span></a><div className="ambient-controls"><Button variant="ghost" className="ambient-control" onClick={()=>setImmersive(v=>!v)} aria-label={immersive?'Mostrar portfólio':'Contemplar o oceano'} aria-pressed={immersive} title={immersive?'Mostrar portfólio (Esc)':'Contemplar o oceano'}>{immersive?<PanelTop size={14}/>:<Waves size={14}/>}<span>{immersive?'VOLTAR':'CONTEMPLAR'}</span></Button><Button variant="ghost" className="ambient-control" onClick={toggleMotion} aria-label={paused?'Ativar animações':'Pausar animações'} aria-pressed={!paused} title={paused?'Ativar animações':'Pausar animações'}>{paused?<Play size={14}/>:<Pause size={14}/>}<span>{paused?'AMBIENTE PAUSADO':'AMBIENTE VIVO'}</span></Button></div></header>
  {immersive&&<div className="contemplate-caption"><p>Permita-se um instante.</p><span>OCEANO, CÓDIGO E UM POUCO DE SILÊNCIO.</span><Button variant="ghost" onClick={()=>setImmersive(false)}>Voltar ao portfólio <ArrowRight size={16}/></Button></div>}
  <div className="observatory" inert={immersive}>
   <aside className="about-panel glass-panel" id="sobre"><span className="eyebrow">01 / QUEM ESTÁ POR TRÁS</span><h2>Sobre mim</h2><div className="about-facts"><span><Code2/>Full Stack Developer</span><span><Compass/>1 ano de experiência prática</span><span><Sparkles/>Experiências web imersivas</span><span><Layers3/>C# · .NET · JavaScript</span></div><p>Transformo ideias em aplicações, conectando tecnologia, criatividade e atenção a cada detalhe.</p><a className="text-link" href="#sobre" onClick={e=>{e.preventDefault();navigate('sobre')}}><span className="circle-icon"><ArrowRight/></span>ME CONHEÇA<ArrowUpRight size={12}/></a><div className="about-footnote"><span/>EM CONSTANTE EVOLUÇÃO</div></aside>
   <section className="hero"><div className="hero-orbit" aria-hidden="true"/><div className="hero-copy"><p className="eyebrow">BEM-VINDO AO MEU UNIVERSO</p><h1>Portfólio</h1><p className="hero-name">RENAN <span>—</span> DESENVOLVEDOR FULL STACK</p><div className="hero-rule"/><p className="hero-description">Cada projeto, um novo mergulho.<br/>Código que transforma ideias<br/>em experiências.</p><a className="dive-button" href="#projetos" onClick={e=>{e.preventDefault();navigate('projetos')}} aria-label="Explorar projetos"><ArrowDown/></a><span className="dive-caption">EXPLORE AS PROFUNDEZAS</span></div></section>
   <section className="projects-panel" id="projetos"><div className="section-label"><h2>Projetos</h2><p>IDEIAS QUE GANHARAM VIDA</p></div><div className="project-grid"><a className="project-card glass-panel" href="https://poesias-emeric.vercel.app/" target="_blank" rel="noopener noreferrer"><span className="project-number">01</span><div className="project-art emeric-art"><BookOpen/><span>Emericpoeta</span><small>PALAVRAS QUE ATRAVESSAM</small></div><div className="project-copy"><h3>Emericpoeta</h3><span className="eyebrow">POESIA & EXPERIÊNCIA</span><p>Um universo literário entre palavras, emoções e tecnologia.</p><span className="card-action">EXPLORAR <ArrowUpRight/></span></div></a><button className="project-card glass-panel" onClick={()=>navigate('arete')}><span className="project-number">02</span><div className="project-art arete-art"><span className="arete-symbol">α</span><span>Areté</span><small>EVOLUIR É UMA JORNADA.</small></div><div className="project-copy"><h3>Areté</h3><span className="eyebrow">SAAS EM DESENVOLVIMENTO</span><p>Um SaaS de produtividade e organização pessoal que está em desenvolvimento.</p><span className="card-action">EM DESENVOLVIMENTO <span className="status-dot"/></span></div></button><button className="project-card glass-panel future-card" onClick={()=>navigate('proximo')}><span className="project-number">03</span><div className="project-art future-art">{profile.nextProject.image?<img className="next-project-image" src={profile.nextProject.image} alt={profile.nextProject.title}/>:<><span>+</span><small>O PRÓXIMO MERGULHO</small></>}</div><div className="project-copy"><h3>{profile.nextProject.title}</h3><span className="eyebrow">{profile.nextProject.category}</span><p>{profile.nextProject.description}</p><span className="card-action">EM CONSTRUÇÃO <span className="status-dot"/></span></div></button></div></section>
   <nav className="universe-nav glass-panel" aria-label="Navegação principal"><p>NAVEGUE PELO UNIVERSO</p><div>{[{id:'inicio',label:'Início',icon:House},{id:'projetos',label:'Projetos',icon:Layers3},{id:'experiencia',label:'Tecnologias',icon:Code2},{id:'sobre',label:'Sobre mim',icon:UserRound},{id:'contato',label:'Contato',icon:Mail}].map(item=><a key={item.id} href={'#'+item.id} className={section===item.id?'active':''} aria-current={section===item.id?'page':undefined} onClick={e=>{e.preventDefault();navigate(item.id)}}><item.icon/><span>{item.label}</span></a>)}</div></nav>
   <section className="library glass-panel" id="livros"><div className="section-label"><h2>Biblioteca do autor</h2><p>OUTRAS FORMAS DE CRIAR UNIVERSOS</p></div><div className="books">{profile.books.map(book=><a key={book.title} className="book-link" href={book.url} target="_blank" rel="noopener noreferrer"><img src={book.image} alt={'Capa do livro '+book.title} width="170" height="259" loading="lazy" decoding="async"/><span>{book.title} <ArrowUpRight/></span></a>)}</div><span className="library-note">DOIS LIVROS PUBLICADOS NA AMAZON</span></section>
  </div><footer className="site-footer"><span>© {new Date().getFullYear()} RENAN</span><span>FEITO COM CÓDIGO. MOVIDO POR CURIOSIDADE.</span></footer>
  {panel&&<Suspense fallback={<div className="panel-loading" role="status">Abrindo universo…</div>}><DetailPanels panel={panel} onClose={closePanel}/></Suspense>}
 </main>;
}


